name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Build
        run: go get -d ./... && go build ./...

      - name: Test
        run: go test -v ./...

      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: "4c4a1c4d-8aa4-411f-aafc-68ee8d62da03"
          heroku_app_name: "intense-sands-21772"
          heroku_email: "ol.kondraschowa@gmail.com"
          usedocker: true

      - name: Wait deploing
        uses: jakejarvis/wait-action@master
        with:
          time: '3s'

      - name: Run API Tests
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          collection: postman/[inst] Lab1.postman_collection.json
          environment: postman/[inst][heroku] Lab1.postman_environment.json
          delayRequest: 50
          reporters: cli

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: badges branch and make dir
        run: |
          git checkout badges 2>/dev/null || git checkout -b badges
          mkdir -p .github/badges

      - name: points badge
        uses: emibcn/badge-action@v1
        with:
          LABEL: 'Points'
          STATUS: ${{ steps.autograder.outputs.Points }}
          COLOR: cyan
          path: '.github/badges/points.svg'

      - name: Commit badge
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add '.github/badges/points.svg'
          git commit -m "Add/Update badge"
        continue-on-error: true

      - name: Push badge commit
        uses: ad-m/github-push-action@master
        if: success()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: badges